const cityCodeMapping = [
  { tw: "臺北市", cityCode: "TPE", en: "Taipei" },
  { tw: "新北市", cityCode: "NWT", en: "NewTaipei" },
  { tw: "基隆市", cityCode: "KEE", en: "Keelung" },
  { tw: "桃園市", cityCode: "TAO", en: "Taoyuan" },
  { tw: "新竹市", cityCode: "HSZ", en: "Hsinchu" },
  { tw: "新竹縣", cityCode: "HSQ", en: "HsinchuCounty" },
  { tw: "苗栗縣", cityCode: "MIA", en: "MiaoliCounty" },
  { tw: "臺中市", cityCode: "TXG", en: "Taichung" },
  { tw: "南投縣", cityCode: "NAN", en: "NantouCounty" },
  { tw: "彰化縣", cityCode: "CHA", en: "ChanghuaCounty" },
  { tw: "雲林縣", cityCode: "YUN", en: "YunlinCounty" },
  { tw: "嘉義市", cityCode: "CYI", en: "Chiayi" },
  { tw: "嘉義縣", cityCode: "CYQ", en: "ChiayiCounty" },
  { tw: "臺南市", cityCode: "TNN", en: "Tainan" },
  { tw: "高雄市", cityCode: "KHH", en: "Kaohsiung" },
  { tw: "屏東縣", cityCode: "PIF", en: "PingtungCounty" },
  { tw: "臺東縣", cityCode: "TTT", en: "TaitungCounty" },
  { tw: "花蓮縣", cityCode: "HUA", en: "HualienCounty" },
  { tw: "宜蘭縣", cityCode: "ILA", en: "YilanCounty" },
  { tw: "澎湖縣", cityCode: "PEN", en: "PenghuCounty" },
  { tw: "金門縣", cityCode: "KIN", en: "KinmenCounty" },
  { tw: "連江縣", cityCode: "LIE", en: "LienchiangCounty" },
];
export { cityCodeMapping };
